CREATE TABLE "predictions" (
	"id" serial PRIMARY KEY NOT NULL,
	"match_id" varchar(100) NOT NULL,
	"home_team_id" varchar(100) NOT NULL,
	"home_team_name" varchar(255) NOT NULL,
	"home_team_crest" text,
	"away_team_id" varchar(100) NOT NULL,
	"away_team_name" varchar(255) NOT NULL,
	"away_team_crest" text,
	"match_date" timestamp NOT NULL,
	"matchday" numeric NOT NULL,
	"venue" varchar(255),
	"home_team_position" numeric,
	"home_team_points" numeric,
	"home_team_played_games" numeric,
	"home_team_won" numeric,
	"home_team_draw" numeric,
	"home_team_lost" numeric,
	"home_team_goals_for" numeric,
	"home_team_goals_against" numeric,
	"home_team_goal_difference" numeric,
	"home_team_avg_corners" numeric(5, 2),
	"home_team_avg_cards" numeric(5, 2),
	"home_team_avg_shots_on_target" numeric(5, 2),
	"home_team_avg_possession" numeric(5, 2),
	"away_team_position" numeric,
	"away_team_points" numeric,
	"away_team_played_games" numeric,
	"away_team_won" numeric,
	"away_team_draw" numeric,
	"away_team_lost" numeric,
	"away_team_goals_for" numeric,
	"away_team_goals_against" numeric,
	"away_team_goal_difference" numeric,
	"away_team_avg_corners" numeric(5, 2),
	"away_team_avg_cards" numeric(5, 2),
	"away_team_avg_shots_on_target" numeric(5, 2),
	"away_team_avg_possession" numeric(5, 2),
	"main_prediction" varchar(50) NOT NULL,
	"main_confidence" varchar(20) NOT NULL,
	"goals_prediction" varchar(50) NOT NULL,
	"goals_confidence" varchar(20) NOT NULL,
	"extra_tip" text NOT NULL,
	"extra_confidence" varchar(20) NOT NULL,
	"corners_prediction" varchar(50),
	"corners_confidence" varchar(20),
	"cards_prediction" varchar(50),
	"cards_confidence" varchar(20),
	"shots_on_target_prediction" varchar(50),
	"shots_on_target_confidence" varchar(20),
	"both_teams_to_score" varchar(50),
	"both_teams_to_score_confidence" varchar(20),
	"justification" text NOT NULL,
	"generated_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "predictions_match_id_unique" UNIQUE("match_id")
);
